# Generated by Django 3.2.13 on 2022-05-06 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deals', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterModelOptions(
            name='deals',
            options={'verbose_name_plural': 'Category'},
        ),
        migrations.RemoveField(
            model_name='deals',
            name='category',
        ),
    ]
