# Generated by Django 3.2.13 on 2022-05-06 14:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('deals', '0002_auto_20220506_1411'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='deals',
            options={'verbose_name_plural': 'Deals'},
        ),
    ]
