# Generated by Django 3.2.13 on 2022-05-06 14:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('deals', '0003_alter_deals_options'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Category',
            new_name='Option',
        ),
    ]
