# Generated by Django 3.2.13 on 2022-05-06 14:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('deals', '0004_rename_category_option'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Option',
        ),
    ]
