# Generated by Django 3.2.13 on 2022-05-06 14:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('deals', '0006_deal1'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='deal1',
            options={},
        ),
        migrations.RemoveField(
            model_name='deal1',
            name='image',
        ),
        migrations.RemoveField(
            model_name='deal1',
            name='image_2',
        ),
        migrations.RemoveField(
            model_name='deal1',
            name='image_url',
        ),
    ]
