# Generated by Django 3.2.13 on 2022-05-07 10:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('deals', '0007_auto_20220506_1433'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Deal1',
        ),
    ]
