# Generated by Django 3.2.13 on 2022-05-07 11:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0013_alter_product_category'),
        ('deals', '0008_delete_deal1'),
    ]

    operations = [
        migrations.AddField(
            model_name='deals',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='products.category'),
        ),
    ]
