# Generated by Django 3.2.13 on 2022-05-06 14:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_auto_20220506_1249'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Person',
        ),
    ]
