# Generated by Django 3.2.13 on 2022-05-20 15:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0014_product_parent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='parent',
        ),
    ]
